
# This is Module 00:PyTorch Fundamentals


In [196]:
print("test")

test


In [197]:
import torch as t
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# All the above libraries are installed in the colab enviroment

print(t.__version__)

2.11.0+cu128


## Introduction to tensors

### Creating tensors

In [198]:
# scalar
scalar=t.tensor(7)
scalar

tensor(7)

In [199]:
scalar.ndim

0

In [200]:
# Get tensor back as python int
scalar.item()

7

In [201]:
# Vector
vector=t.tensor([7,7])
vector

tensor([7, 7])

In [202]:
vector.ndim

1

In [203]:
# Matrix
MATRIX=t.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [204]:
MATRIX.ndim

2

In [205]:
MATRIX[0]

tensor([7, 8])

In [206]:
MATRIX.shape

torch.Size([2, 2])

In [207]:
# TENSOR
TENSOR=t.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[3,4,6],[12,89,13],[34,13,78]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[ 3,  4,  6],
         [12, 89, 13],
         [34, 13, 78]]])

In [208]:
TENSOR.ndim

3

In [209]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random tensors
Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data

## Colab Keyboard Shortcuts

*   **Ctrl + M A**: Insert code cell above
*   **Ctrl + M B**: Insert code cell below
*   **Ctrl + M M**: Change cell to markdown
*   **Ctrl + M Y**: Change cell to code
*   **Ctrl + M D**: Delete cell
*   **Ctrl + M Z**: Undo last cell operation
*   **Ctrl + M C**: Cut cell
*   **Ctrl + M V**: Paste cell
*   **Ctrl + M H**: Show keyboard shortcuts
*   **Ctrl + M I**: Interrupt execution
*   **Ctrl + S**: Save notebook
*   **Ctrl + Enter**: Run selected cell
*   **Shift + Enter**: Run selected cell and move to next
*   **Alt + Enter**: Run selected cell and insert code cell below

In [210]:
# create a random tensor of size (3,4)
random_tensor=t.rand(3,3,10)
random_tensor

tensor([[[0.2129, 0.3735, 0.6400, 0.2422, 0.5736, 0.9003, 0.3588, 0.6926,
          0.2797, 0.9562],
         [0.5152, 0.4281, 0.9212, 0.9464, 0.6070, 0.0817, 0.9656, 0.9057,
          0.1144, 0.9295],
         [0.6624, 0.6275, 0.0898, 0.4555, 0.5998, 0.3655, 0.8705, 0.3339,
          0.9351, 0.6578]],

        [[0.7932, 0.1647, 0.1617, 0.6752, 0.0800, 0.6553, 0.8760, 0.0299,
          0.4451, 0.7914],
         [0.8557, 0.0075, 0.6095, 0.1834, 0.0183, 0.8150, 0.0771, 0.9944,
          0.2668, 0.2957],
         [0.8328, 0.2882, 0.5896, 0.1833, 0.8901, 0.9669, 0.4933, 0.6334,
          0.6186, 0.7330]],

        [[0.0198, 0.5982, 0.3650, 0.2365, 0.3699, 0.0759, 0.5601, 0.1584,
          0.0301, 0.7392],
         [0.0956, 0.4371, 0.9707, 0.5796, 0.3762, 0.0126, 0.7138, 0.9688,
          0.5561, 0.4658],
         [0.5055, 0.5019, 0.3376, 0.8389, 0.5293, 0.7991, 0.1030, 0.7473,
          0.2284, 0.7047]]])

In [211]:
random_tensor.ndim

3

In [212]:
random_tensor.shape

torch.Size([3, 3, 10])

In [213]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=t.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [214]:
RANDOM_TENSOR=t.rand((3,2,5,4))

In [215]:
RANDOM_TENSOR

tensor([[[[0.6781, 0.0889, 0.0698, 0.6036],
          [0.9435, 0.8138, 0.8460, 0.0300],
          [0.4522, 0.3092, 0.0041, 0.7984],
          [0.3577, 0.9634, 0.1625, 0.5054],
          [0.3460, 0.7844, 0.6274, 0.4474]],

         [[0.7668, 0.4076, 0.5798, 0.8984],
          [0.3054, 0.0304, 0.1771, 0.1112],
          [0.2861, 0.9711, 0.2871, 0.7517],
          [0.0628, 0.9350, 0.6747, 0.9802],
          [0.6449, 0.3553, 0.8698, 0.5682]]],


        [[[0.2089, 0.3158, 0.7884, 0.9246],
          [0.6445, 0.7928, 0.2059, 0.9491],
          [0.5808, 0.8691, 0.6162, 0.3607],
          [0.8913, 0.0648, 0.3469, 0.7164],
          [0.6239, 0.6725, 0.5448, 0.5831]],

         [[0.5515, 0.4911, 0.7843, 0.7781],
          [0.7727, 0.2463, 0.4231, 0.4002],
          [0.2929, 0.4513, 0.6999, 0.0682],
          [0.7311, 0.9622, 0.1689, 0.1331],
          [0.4633, 0.9933, 0.3497, 0.6036]]],


        [[[0.0774, 0.8807, 0.4309, 0.5646],
          [0.7708, 0.2550, 0.8993, 0.4814],
          [0.6143, 0

### Zeroes and Ones

In [216]:
### create a tensor of all zeroes
ZEROES=t.zeros(size=(3,4))
ZEROES

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [217]:
### Create a tensor of all ones
ONES=t.ones(3,4)
ONES

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [218]:
ONES.dtype

torch.float32

### Creating a range

In [219]:
RANGE=t.arange(10,10001,10).reshape((10,10,10))
RANGE.shape,RANGE.ndim

(torch.Size([10, 10, 10]), 3)

In [220]:
RANGE

tensor([[[   10,    20,    30,    40,    50,    60,    70,    80,    90,   100],
         [  110,   120,   130,   140,   150,   160,   170,   180,   190,   200],
         [  210,   220,   230,   240,   250,   260,   270,   280,   290,   300],
         [  310,   320,   330,   340,   350,   360,   370,   380,   390,   400],
         [  410,   420,   430,   440,   450,   460,   470,   480,   490,   500],
         [  510,   520,   530,   540,   550,   560,   570,   580,   590,   600],
         [  610,   620,   630,   640,   650,   660,   670,   680,   690,   700],
         [  710,   720,   730,   740,   750,   760,   770,   780,   790,   800],
         [  810,   820,   830,   840,   850,   860,   870,   880,   890,   900],
         [  910,   920,   930,   940,   950,   960,   970,   980,   990,  1000]],

        [[ 1010,  1020,  1030,  1040,  1050,  1060,  1070,  1080,  1090,  1100],
         [ 1110,  1120,  1130,  1140,  1150,  1160,  1170,  1180,  1190,  1200],
         [ 1210,  1220,  1

### tensors-like

In [221]:
one_to_ten=t.arange(1,11,1)
ten_zeros=t.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [222]:
ten_ones=t.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### tensor datatypes

In [223]:
float_32_tensor=t.tensor([3.0,6.0,9.0],dtype=None,device="cuda",requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [224]:
float_32_tensor.dtype

torch.float32

In [225]:
float_16_tensor=float_32_tensor.type(t.half)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [226]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [227]:
int_32_tensor=t.tensor([3,6,9],dtype=t.int32,device="cuda",requires_grad=False)
int_32_tensor

tensor([3, 6, 9], device='cuda:0', dtype=torch.int32)

In [228]:
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [229]:
float_32_tensor/int_32_tensor

tensor([1., 1., 1.], device='cuda:0')

### Getting information from tensors

In [230]:
some_tensor=t.rand(3,4)
some_tensor

tensor([[0.5528, 0.1865, 0.0258, 0.1709],
        [0.0721, 0.7939, 0.0463, 0.8601],
        [0.2965, 0.7089, 0.6811, 0.4760]])

In [231]:
# find details about some_tensor
print(f"Size : {some_tensor.size()}")
print(f"Shape : {some_tensor.shape}")
print(f"Datatype : {some_tensor.dtype}")
print(f"Device : {some_tensor.device}")
print(f"Requires Gradient : {some_tensor.requires_grad}")

Size : torch.Size([3, 4])
Shape : torch.Size([3, 4])
Datatype : torch.float32
Device : cpu
Requires Gradient : False


In [232]:
## Manipulating tensors
tensor=t.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [233]:
tensor-10

tensor([-9, -8, -7])

In [234]:
tensor*10

tensor([10, 20, 30])

In [235]:
tensor2=t.tensor([[1,4,5],
                  [2,5,6],
                  [1,1,1]])
t.matmul(tensor,tensor2)

tensor([ 8, 17, 20])

In [236]:
%%time
tensor@tensor2

CPU times: user 55 µs, sys: 0 ns, total: 55 µs
Wall time: 58.9 µs


tensor([ 8, 17, 20])

In [237]:
%%time
t.matmul(tensor,tensor2)

CPU times: user 379 µs, sys: 48 µs, total: 427 µs
Wall time: 1.26 ms


tensor([ 8, 17, 20])

In [238]:
t1=t.rand(1,3)
t2=t.rand(2,3)
t1@t2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 2x3)

In [267]:
t1=t.rand(4,3)
t2=t.rand(3,2)
t1@t2

tensor([[0.3971, 0.4725],
        [0.5002, 0.9106],
        [0.7827, 1.1312],
        [0.0779, 0.2215]])

In [268]:
t1=t.rand(1,3)
t2=t.rand(2,3)
t2=t2.T
t1@t2

tensor([[1.1026, 1.3057]])

Finding the min,max,mean,sum, etc ...

In [269]:
t1=t.tensor([[1,2,3],
             [4,5,6],
             [7,8,9]])
t1.sum(axis=0)

tensor([12, 15, 18])

In [270]:
t1.sum(axis=1)

tensor([ 6, 15, 24])

In [271]:
t1.sum()

tensor(45)

In [272]:
t1.max()

tensor(9)

In [273]:
t1.max(axis=0),t1.max(axis=1)

(torch.return_types.max(
 values=tensor([7, 8, 9]),
 indices=tensor([2, 2, 2])),
 torch.return_types.max(
 values=tensor([3, 6, 9]),
 indices=tensor([2, 2, 2])))

In [274]:
t1=t1.type(t.float16)
t1.mean(),t1.mean(axis=0),t1.mean(axis=1)

(tensor(5., dtype=torch.float16),
 tensor([4., 5., 6.], dtype=torch.float16),
 tensor([2., 5., 8.], dtype=torch.float16))

### Positional min,max (argmin,argmax)

In [275]:
t1.argmax(),t1.argmin()

(tensor(8), tensor(0))

In [276]:
t1.argmax(axis=0),t1.argmin(axis=0)

(tensor([2, 2, 2]), tensor([0, 0, 0]))

In [277]:
t1.argmax(axis=1),t1.argmin(axis=1)

(tensor([2, 2, 2]), tensor([0, 0, 0]))

### Reshaping,stacking,squeezing,unsqueezing

In [278]:
x=t.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [279]:
## add an extra dimension
x_reshaped=x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [280]:
# Change the view
z=x.view(3,3)
z,z.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [281]:
z[0][1]=10
x

tensor([ 1, 10,  3,  4,  5,  6,  7,  8,  9])

In [282]:
# Stack tensors on top of each other
x_stacked=t.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 1, 10,  3,  4,  5,  6,  7,  8,  9],
        [ 1, 10,  3,  4,  5,  6,  7,  8,  9],
        [ 1, 10,  3,  4,  5,  6,  7,  8,  9],
        [ 1, 10,  3,  4,  5,  6,  7,  8,  9]])

In [283]:
t.vstack([x,x])

tensor([[ 1, 10,  3,  4,  5,  6,  7,  8,  9],
        [ 1, 10,  3,  4,  5,  6,  7,  8,  9]])

In [284]:
t.hstack([x,x])

tensor([ 1, 10,  3,  4,  5,  6,  7,  8,  9,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [285]:
x.squeeze()

tensor([ 1, 10,  3,  4,  5,  6,  7,  8,  9])

In [286]:
x.unsqueeze(dim=1)

tensor([[ 1],
        [10],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [287]:
x.unsqueeze(dim=0)

tensor([[ 1, 10,  3,  4,  5,  6,  7,  8,  9]])

In [288]:
y=t.tensor([[1,2,3,4]])
y.squeeze()

tensor([1, 2, 3, 4])

In [289]:
z=t.tensor([[1],[2],[3],[4]])
z.squeeze()

tensor([1, 2, 3, 4])

In [290]:
# torch.permute
M=t.rand(size=(2,4,3))
M_p=M.permute((0,2,1))

In [291]:
M

tensor([[[0.5912, 0.3525, 0.3071],
         [0.1697, 0.0974, 0.8774],
         [0.4607, 0.7697, 0.0876],
         [0.7329, 0.8238, 0.8275]],

        [[0.9565, 0.8889, 0.1632],
         [0.2684, 0.1920, 0.9836],
         [0.9867, 0.3540, 0.1390],
         [0.1625, 0.8021, 0.9610]]])

In [292]:
M_p

tensor([[[0.5912, 0.1697, 0.4607, 0.7329],
         [0.3525, 0.0974, 0.7697, 0.8238],
         [0.3071, 0.8774, 0.0876, 0.8275]],

        [[0.9565, 0.2684, 0.9867, 0.1625],
         [0.8889, 0.1920, 0.3540, 0.8021],
         [0.1632, 0.9836, 0.1390, 0.9610]]])

In [293]:
M[0][0][1]+=100
M_p

tensor([[[5.9121e-01, 1.6973e-01, 4.6072e-01, 7.3292e-01],
         [1.0035e+02, 9.7420e-02, 7.6969e-01, 8.2384e-01],
         [3.0713e-01, 8.7742e-01, 8.7639e-02, 8.2749e-01]],

        [[9.5650e-01, 2.6843e-01, 9.8672e-01, 1.6246e-01],
         [8.8887e-01, 1.9204e-01, 3.5402e-01, 8.0214e-01],
         [1.6324e-01, 9.8357e-01, 1.3901e-01, 9.6096e-01]]])

### Indexing

In [294]:
M[0][0][1]-=100

In [295]:
M

tensor([[[0.5912, 0.3525, 0.3071],
         [0.1697, 0.0974, 0.8774],
         [0.4607, 0.7697, 0.0876],
         [0.7329, 0.8238, 0.8275]],

        [[0.9565, 0.8889, 0.1632],
         [0.2684, 0.1920, 0.9836],
         [0.9867, 0.3540, 0.1390],
         [0.1625, 0.8021, 0.9610]]])

In [296]:
M[:,0,:2]

tensor([[0.5912, 0.3525],
        [0.9565, 0.8889]])

### PyTorch vs NumPy

In [299]:
array=np.array([1.0,2.0,3.0])
tensor=t.from_numpy(array)
tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [300]:
t.arange(1.0,8.0).dtype

torch.float32

In [301]:
# change the value of array
array=array+1
tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [302]:
array

array([2., 3., 4.])

In [304]:
tensor=t.ones(7)
numpy_tensor=tensor.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

### Reproducability

In [332]:
t.manual_seed(42)
t.rand(3,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [333]:
t.rand(3,3)

tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

### Running tensors and pytorch on GPU's

In [335]:
t.cuda.is_available()

True

In [336]:
# setup device agnostic code
device="cuda" if t.cuda.is_available() else "cpu"

In [337]:
# count gpu's
t.cuda.device_count()

1

### Putting tensors on the gpu

In [338]:
tn=t.tensor([1,2,3],device=device)
tn

tensor([1, 2, 3], device='cuda:0')

In [340]:
tensor_back_on_cpu=tn.cpu()
tensor_back_on_cpu.numpy()

array([1, 2, 3])